### ISSUE TITLE
Randomly a 404 is delivered instead of the correct graph.

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid-handler-file#4]
'''
0|npm      | ::ffff:172.18.0.4 - - [17/Oct/2017:02:33:53 +0000] "GET / HTTP/1.1" 200 13711 "-" "-"
0|npm      | ::ffff:172.18.0.4 - - [17/Oct/2017:02:38:53 +0000] "GET / HTTP/1.1" 200 13711 "-" "-"
0|npm      | ::ffff:172.18.0.4 - - [17/Oct/2017:02:42:29 +0000] "GET /robots.txt HTTP/1.1" 404 13158 "-" "-"
0|npm      | ::ffff:172.18.0.4 - - [17/Oct/2017:02:42:29 +0000] "GET / HTTP/1.1" 404 13158 "-" "-"
0|npm      | ::ffff:172.18.0.4 - - [17/Oct/2017:02:45:13 +0000] "GET /robots.txt HTTP/1.1" 404 13158 "-" "-"
0|npm      | ::ffff:172.18.0.4 - - [17/Oct/2017:02:45:14 +0000] "GET / HTTP/1.1" 404 13158 "-" "-"
0|npm      | ::ffff:172.18.0.4 - - [17/Oct/2017:02:45:14 +0000] "GET / HTTP/1.1" 200 13711 "-" "-"
'''

**Comment by bergos** [comment]
@l00mi I think this was a problem with the docker image not being able to access the file, right? Can we close this issue?

**Comment by l00mi** [comment]
I did not see the problem anymore since a long time. Not sure what it was finally. But gont.ch on the latest trifid did not show it anymore.
